spring.application.name=physcolog
spring.jpa.hibernate.ddl-auto=update
spring.security.enabled=false
upload.path=src/main/resources/static/upload/images
//upload.path=static/upload/images/
spring.datasource.url=jdbc:postgresql://localhost:5432/physcolog
spring.datasource.username=postgres
spring.datasource.password=********
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
